### ISSUE TITLE
homebrew_installed_packages not installed if homebrew_cask_apps encounters apps which are already installed

### ISSUE THREAD

**Issue by micalexander** [geerlingguy/ansible-role-homebrew#122]
https://github.com/geerlingguy/mac-dev-playbook/issues/57#event-2584004944

This can be easily reproduced by having something like say firefox installed and running a role directly after this one from the same playbook. This ansible-role-homebrew will finish but the following role will not execute due to the previous error of firefox already being installed

**Comment by micalexander** [comment]
@geerlingguy any ideas?

**Comment by davidbenton** [comment]
Installing and re-installing a cask usually works without issue, but I found an edge case today where it failed with "Warning: Cask 'java' is already installed" (and same with two other casks). Turned out not to be an issue with ansible-role-homebrew, but I found a solution, and maybe it will help others too.

Check output of
```
brew cask list [CASK]
```

There have been some deprecations in how casks are defined and old casks can throw errors when ansible checks if they're installed. The ansible homebrew module [uses](https://github.com/ansible-collections/community.general/blob/5d226f86b63297f533753c78d470cbe5cc23b309/plugins/modules/packaging/os/homebrew_cask.py#L456) `brew cask list [CASK]` to check for already-installed casks. This gives a useful error message, but it is not captured. This means  you end up with a failure, but the `msg` is the "already installed" output of `brew cask install [CASK]`. That's misleading, as it's not the output from the failed command, and reads like a success message in the context.

In my case, I had three failing casks, which ended up being two separate issues: an [outdated `depends_on`](https://github.com/Homebrew/homebrew-cask/issues/58046) and two that used the [deprecated `undent`](https://github.com/Homebrew/homebrew-cask/issues/49716#issuecomment-410842187). The fixes listed in those issues got me going, but the important thing is to check `brew cask list [CASK]` for errors.
