### ISSUE TITLE
Q: Is there way to specify installed package version?

### ISSUE THREAD

**Issue by tedgonzalez** [geerlingguy/ansible-role-homebrew#133]

**Comment by tedgonzalez** [comment]
activity

**Comment by tedgonzalez** [comment]
activity

**Comment by darthwalsh** [comment]
The ability to install a version of a package doesn't seem to be supported by `brew`. I spent a while in this train-wreck of a thread: https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula and it seems that `brew versions` was the solution until it was deprectated, then `brew switch` until that was disabled...

I was able to run `brew install postgresql@9.5 && brew link --force postgresql@9.5` which worked, but that's only because there are special '@' versions of postgresql. Compare that with cmake:

```
$ brew search postgresql@
==> Formulae
postgresql            postgresql@10         postgresql@11 ✔       postgresql@12         postgresql@9.4        postgresql@9.5 ✔      postgresql@9.6
==> Casks
navicat-for-postgresql
$ brew search cmake@
==> Formulae
cmake                                                                           kde-extra-cmake-modules
==> Casks
cmake
```

You can [grovel through github history](https://itnext.io/how-to-install-an-older-brew-package-add141e58d32) to find a specific package, i.e. for [cmake](https://stackoverflow.com/q/58148541/771768), but that seems too automagical to expect an ansible module to do for me.

**Comment by tedgonzalez** [comment]
🚴🏻‍♂️

**Comment by geerlingguy** [comment]
Closing all issues in this repository in preparation for a migration to `geerlingguy.mac`—see https://github.com/geerlingguy/ansible-role-homebrew/issues/166
