### ISSUE TITLE
Add a cleanup task.

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-homebrew#40]
`brew cask cleanup` should be ran before installing applications via cask to prevent attempted execution of corrupt or incomplete applications.

The task could be optional based off a boolean, and it also helps free up disk space.
In my case running it on my work mac gave me an additional gigabyte of storage.

Thoughts?

**Comment by elliotweiser** [comment]
There is definitely value in this @fubarhouse. Saving disk space or avoiding corrupt installations makes sense, as long as doing so is configurable. The opportunity cost is re-downloading (potentially large and potentially several) files that would have otherwise been cached. I'm coding up a PR that will optionally clean the package and cask cache before and/or after the installation.

**Comment by elliotweiser** [comment]
Released in 2.6.0
